//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeFoneApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUMUON
    {
        public string IDPM { get; set; }
        public string Mssv { get; set; }
        public string IDBook { get; set; }
        public Nullable<System.DateTime> NGM { get; set; }
        public Nullable<System.DateTime> NGHH { get; set; }
        public Nullable<decimal> FeeM { get; set; }
        public string Status { get; set; }
    
        public virtual BOOK BOOK { get; set; }
        public virtual READER READER { get; set; }
    }
}
