//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeFoneApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUPHAT
    {
        public string IDPP { get; set; }
        public string Mssv { get; set; }
        public Nullable<decimal> FeeP { get; set; }
        public string Content { get; set; }
    
        public virtual READER READER { get; set; }
    }
}
